//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.26 at 07:52:23 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.uidai.gov.in/kyc/uid-kyc-response/1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package in.gov.uidai.core.model.xsd.kyc.uid_kyc_response._1;
